title: DHS 2027
description: Design History Society Annual Conference

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v4.0.2"

plugins:
  - jekyll-include-cache

collections:
  talks:
    output: true
    permalink: /program/:name/
  speakers:
    output: true
  rooms:
    output: true
  venues:
    output: true

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk

  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker

  - scope:
      path: ""
      type: rooms
    values:
      layout: room

  - scope:
      path: ""
      type: venues
    values:
      layout: venue

conference:
  lang: en
  tz: "+01:00"
  days:
    - name: Day Zero
      date: 2026-09-02
    - name: Day One
      date: 2026-09-03
    - name: Day Two
      date: 2026-09-04
    - name: Day Three
      date: 2026-09-05
    - name: Post-conference Tours
      date: 2026-09-06
  rooms:
    - name: Room A
    - name: Room B
    - name: Room C
